version: '3.8'

networks:
  gymapp-network:
    driver: bridge

services:
  frontend:
    container_name: gymapp-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - gymapp-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_API_URL=http://localhost:5000/api
    restart: always